[package]
name = "rustidea"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = "0.18.0"
egui = "0.18.1"
whoami = "1.2.1"
winapi = "0.3.9"

[profile.release]
codegen-units = 1
lto = true